language: python
python:
- "3.5"

sudo: required

before_install:
- pip install mkdocs
- pip install mkdocs-material

install:
- mkdocs build --clean

script:
- git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/Open-EO/openeo-api.git gh-pages
- cd gh-pages
- if [[ $TRAVIS_BRANCH == 'master' ]] ; then rm -rf !(v) && cp -R ../site/* ./ ; fi
- if [[ $TRAVIS_BRANCH != 'master' ]] ; then rm -rf v/$TRAVIS_BRANCH && mkdir -p v/$TRAVIS_BRANCH/ && cp -R ../site/* v/$TRAVIS_BRANCH/ ; fi
- git config user.name "Travis CI Documentation Builder"
- git config user.email "m.mohr@uni-muenster.de"
- git add .
- git commit -m "Automated documentation build[ci skip]"
- git push --force "$GITHUB_TOKEN@github.com:Open-EO/openeo-api.git" gh-pages:gh-pages
