language: python
python:
- "3.5"

sudo: required

before_install:
- pip install mkdocs
- pip install mkdocs-material

install:
- mkdocs build --clean

script:
- git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/Open-EO/openeo-api.git gh-pages
- if [[ $TRAVIS_BRANCH == 'master' ]] ; then cd gh-pages/ && rm -rf !(v) && cd - && cp -R site/* gh-pages/ ; fi
- if [[ $TRAVIS_BRANCH != 'master' ]] ; then rm -rf gh-pages/v/$TRAVIS_BRANCH && mkdir -p gh-pages/v/$TRAVIS_BRANCH/ && cp -R site/* gh-pages/v/$TRAVIS_BRANCH/ ; fi
- git config user.name "Travis CI Documentation Builder"
- git config user.email "m.mohr@uni-muenster.de"
- cd gh-pages && git add .
- git commit -m "Automated documentation build[ci skip]"
- git push --force "${GH_REF}" gh-pages:gh-pages
