language: python

python:
- "3.5"

node_js: 8

sudo: required

before_install:
- pip install mkdocs
- pip install mkdocs-material
- pip install pymdown-extensions
- pip install pygments
- npm install -g asyncapi-docgen

install:
- mv CHANGELOG.md docs/changelog.md
- mkdocs build --clean
- cp openapi.json site/
- cp processes.json site/
- rm -f site/apireference/index.html
- rm -f site/processreference/index.html
- rm -f site/apireference-subscriptions/index.html
- mv docs/apireference.html site/apireference/index.html
- mv docs/processreference.html site/processreference/index.html
- adg subscriptions.json -o site/apireference-subscriptions

script:
- git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/Open-EO/openeo-api.git gh-pages
- cd gh-pages
- if [[ $TRAVIS_BRANCH == 'master' ]] ; then rm -rf !(v) && cp -R ../site/* ./ ; fi
- if [[ $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then rm -rf v/$TRAVIS_BRANCH/ && mkdir -p v/$TRAVIS_BRANCH/ && cp -R ../site/* v/$TRAVIS_BRANCH/ ; fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    all_branches: true