sudo: required
services:
- docker

env:
  global:
  - GIT_NAME: "Travis CI Documentation Builder"
  - GIT_EMAIL: marius.appel@uni-muenster.de
  - GH_REF: git@github.com:Open-EO/openeo-api-poc.git

before_install:
- openssl aes-256-cbc -K $encrypted_cc1eefc65230_key -iv $encrypted_cc1eefc65230_iv -in docs/deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- echo -e "Host github \n\t HostName github.com \n\t IdentityFile $TRAVIS_BUILD_DIR/deploy_key" >> ~/.ssh/config

install:
- cd docs
- docker build -t openeo/apidocs .

script:
- rm -rf site
- docker run -v $PWD:/shared openeo/apidocs
- cd site
- eval "$(ssh-agent -s)"
- ssh-add $TRAVIS_BUILD_DIR/deploy_key
- git init
- git config user.name "Travis CI Documentation Builder"
- git config user.email "marius.appel@uni-muenster.de"
- git add .
- git commit -m "Automated documentation build[ci skip]"
- git push --force "${GH_REF}" master:gh-pages



