site_name: openEO Documentation
pages:
  - Prologue:
    - Introduction: index.md
    - Glossary: glossary.md
    - Contributor Code of Conduct: codeofconduct.md
    - Software Development Guidelines: softwareguidelines.md
  - Getting started:
    - Users: gettingstarted-users.md
    - Back-end providers: gettingstarted-backends.md
    - Examples / Proof of Concept: poc.md
  - Architecture: arch.md
  - Features:
    - User Management and Accounting: usermanagement.md
    - Jobs: jobs.md
    - UDFs: udfs.md
  - API:
    - Specification Guidelines: apiguidelines.md
    - Error handling: errors.md
    - CORS: cors.md
    - Process Graphs: processgraphs.md
  - API Reference: apireference.md
theme:
  name: 'material'
repo_url: https://github.com/Open-EO/openeo-api
use_directory_urls: false
markdown_extensions:
  - admonition