site_name: openEO Documentation
pages:
  - Prologue:
    - Introduction: index.md
    - Glossary: glossary.md
    - Contributor Code of Conduct: codeofconduct.md
  - Getting started:
    - Users: gettingstarted-users.md
    - Back-end Providers: gettingstarted-backends.md
    - Client Developers: gettingstarted-clients.md
    - Examples (proof-of-concept): examples-poc.md
  - Architecture: arch.md
  - Features:
    - User Management and Accounting: usermanagement.md
    - Jobs: jobs.md
    - UDFs: udfs.md
  - Development guidelines:
    - Software Development: guidelines-software.md
    - Client Library Development: guidelines-clients.md
    - API Specification: guidelines-api.md
  - API:
    - Processes
      - Introduction: processes.md
      - Reference: processreference.md
    - Process Graphs: processgraphs.md
    - Error Handling: errors.md
    - CORS: cors.md
  - API Reference: apireference.md
theme:
  name: 'material'
repo_url: https://github.com/Open-EO/openeo-api
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences