sudo: required

services:
  - docker

install:
  - docker build -t openeo/apidocs .

script:
- docker run -v $PWD:/shared openeo/apidocs

deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
