site_name: openEO - Concepts & API
pages:
  - Home: index.md
  - Glossary: glossary.md
  - Architecture and Microservices: arch.md
  - API Guidelines:
    - General Guidelines: guidelines.md
    - Error handling: errors.md
    - CORS: cors.md
  - API Features:
    - User Management and Accounting: usermanagement.md
    - Jobs: jobs.md
    - UDFs: udfs.md
    - Process Graphs: processgraphs.md
    - Constraints: views.md
  - API Reference (Official): apireference.md
  - API Reference (Alternative): https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/Open-EO/openeo-api/0.3.0/openapi.json
  - Proof of Concept: poc.md
theme: readthedocs
repo_url: https://github.com/Open-EO/openeo-api
site_favicon: favicon.ico
use_directory_urls: false # make links working on local filesystem too