site_name: openEO - Concepts & API
pages:
  - Home: index.md
  - Glossary: glossary.md
  - Architecture and Microservices: arch.md
  - Jobs: jobs.md
  - Process Graphs: processgraphs.md
  - UDFs: udfs.md
  - Data Views: views.md
  - CORS: cors.md
  - Proof of Concept: poc.md
  - API Reference: apireference.md
theme: readthedocs
repo_url: https://github.com/Open-EO/openeo-api
site_favicon: favicon.ico
use_directory_urls: false # make links working on local filesystem too