site_name: openEO Documentation
pages:
  - Prologue:
    - Introduction: index.md
    - Glossary: glossary.md
    - Contributor Code of Conduct: code_of_conduct.md
    - Software Development Guidelines: software_guidelines.md
  - Getting started:
    - Users: getting_started/users.md
    - Back-end providers: getting_started/backends.md
    - Examples / Proof of Concept: poc.md
  - Architecture: arch.md
  - Features:
    - User Management and Accounting: usermanagement.md
    - Jobs: jobs.md
    - UDFs: udfs.md
  - Core API:
    - Specification Guidelines: api_guidelines.md
    - Error handling: errors.md
    - CORS: cors.md
    - Process Graphs: processgraphs.md
  - API Reference: apireference.md
theme:
  name: 'material'
repo_url: https://github.com/Open-EO/openeo-api
site_favicon: favicon.ico
use_directory_urls: false
markdown_extensions:
  - admonition